<?php  defined('SYSPATH') or die('No direct script access.');
/**
 * Created by JetBrains PhpStorm.
 * User : Andrew Scherbakov
 * Date : 05.11.12
 * Time : 10:53
 * File : oauth.php
 *
 * @name oauth
 * @packages Wordpress/ThemeFramework/oauth
 * @subpackage
 * @category
 * @author Andrew Scherbakov
 * @version 0.1
 * @copyright ®©Andrew Scherbakov
 * To change this template use File | Settings | File Templates.
 */
return array(
  'dropbox'    => array(
    'oauth_version'                => '1.0',
    'request_token_url'            => 'https://api.dropbox.com/1/oauth/request_token',
    'dialog_url'                   => 'https://www.dropbox.com/1/oauth/authorize',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'https://api.dropbox.com/1/oauth/access_token',
    'authorization_header'         => FALSE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => '',
    'method_url'                   => 'https://api.dropbox.com/1/{METHOD_NAME}?{METHOD_URI}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'facebook'   => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    'dialog_url'                   => 'https://www.facebook.com/dialog/oauth?client_id={CLIENT_ID}&scope={SCOPE}&state={STATE}&redirect_uri={REDIRECT_URI}',
    'append_state_to_redirect_uri' => '',
    'access_token_url'             => 'https://graph.facebook.com/oauth/access_token',
    'authorization_header'         => FALSE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => 'publish_actions',
    'method_url'                   => 'https://graph.facebook.com/{METHOD_NAME}?{METHOD_URI}&access_token={ACCESS_TOKEN}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'flickr'     => array(
    'oauth_version'                => '1.0a',
    'request_token_url'            => 'http://www.flickr.com/services/oauth/request_token',
    'dialog_url'                   => 'http://www.flickr.com/services/oauth/authorize',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'http://www.flickr.com/services/oauth/access_token',
    'authorization_header'         => FALSE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => '',
    'method_url'                   => 'http://api.flickr.com/services/rest/?method={METHOD_NAME}&{METHOD_URI}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'foursquare' => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    'dialog_url'                   => 'https://foursquare.com/oauth2/authorize?client_id={CLIENT_ID}&scope={SCOPE}&response_type=code&redirect_uri={REDIRECT_URI}&state={STATE}',
    'append_state_to_redirect_uri' => '',
    'access_token_url'             => 'https://foursquare.com/oauth2/access_token',
    'authorization_header'         => TRUE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => '',
    'method_url'                   => 'https://api.foursquare.com/v2/{METHOD_NAME}?{METHOD_URI}&oauth_token={ACCESS_TOKEN}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'github'     => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    'dialog_url'                   => 'https://github.com/login/oauth/authorize?client_id={CLIENT_ID}&redirect_uri={REDIRECT_URI}&scope={SCOPE}&state={STATE}',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'https://github.com/login/oauth/access_token',
    'authorization_header'         => FALSE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => 'user',
    'method_url'                   => 'https://api.github.com/{METHOD_NAME}?{METHOD_URI}&access_token={ACCESS_TOKEN}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'google'     => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    'dialog_url'                   => 'https://accounts.google.com/o/oauth2/auth?response_type=code&client_id={CLIENT_ID}&redirect_uri={REDIRECT_URI}&scope={SCOPE}&state={STATE}',
    'append_state_to_redirect_uri' => '',
    'access_token_url'             => 'https://accounts.google.com/o/oauth2/token',
    'authorization_header'         => FALSE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => 'https://www.googleapis.com/auth/plus.me',
    'method_url'                   => 'https://www.googleapis.com/plus/v1/{METHOD_NAME}?{METHOD_URI}&access_token={ACCESS_TOKEN}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'iVkontakte'   => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    //'dialog_url'                   => 'https://oauth.vk.com/authorize?client_id={CLIENT_ID}&scope={SCOPE}&redirect_uri={REDIRECT_URI}&response_type=token&display=popup',
    'dialog_url'                   => 'https://oauth.vk.com/authorize?client_id={CLIENT_ID}&scope={SCOPE}&redirect_uri={REDIRECT_URI}&response_type=token&display=popup',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'https://oauth.vk.com/access_token',
    'authorization_header'         => FALSE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => 'friends,wall,offline,video,groups,stats,status',
    'method_url'                   => 'https://api.vk.com/method/{METHOD_NAME}?{METHOD_URI}&access_token={ACCESS_TOKEN}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'linkedin'      => array(
    'oauth_version'                => '1.0a',
    'request_token_url'            => 'https://api.linkedin.com/uas/oauth/requestToken?scope=r_fullprofile+r_emailaddress+r_contactinfo+rw_nus',
    'dialog_url'                   => 'https://api.linkedin.com/uas/oauth/authenticate',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'https://api.linkedin.com/uas/oauth/accessToken',
    'authorization_header'         => TRUE,
    'url_parameters'               => TRUE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => 'r_basicprofile+r_emailaddress',
    'method_url'                   => 'http://api.linkedin.com/v1/{METHOD_NAME}?{METHOD_URI}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'moimir'   => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    'dialog_url'                   => 'https://connect.mail.ru/oauth/authorize?client_id={CLIENT_ID}&response_type=code&display=mobile&scope={SCOPE}&state={STATE}&redirect_uri={REDIRECT_URI}',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'https://connect.mail.ru/oauth/token',
    'authorization_header'         => FALSE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => 'stream',
    'method_url'                   => 'http://www.appsmail.ru/platform/api?method={METHOD_NAME}&secure=1&app_id={CLIENT_ID}&{METHOD_URI}&session_key={ACCESS_TOKEN}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'microsoft'  => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    'dialog_url'                   => 'https://login.live.com/oauth20_authorize.srf?client_id={CLIENT_ID}&scope={SCOPE}&response_type=code&redirect_uri={REDIRECT_URI}&state={STATE}',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'https://login.live.com/oauth20_token.srf',
    'authorization_header'         => TRUE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'method_url'                   => 'https://www.googleapis.com/plus/v1/{METHOD_NAME}?{METHOD_URI}&access_token={ACCESS_TOKEN}',
    'scope'                        => '',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'odnoclassniki'   => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    'dialog_url'                   => 'http://www.odnoklassniki.ru/oauth/authorize?client_id={CLIENT_ID}&response_type=code&display=mobile&scope={SCOPE}&state={STATE}&redirect_uri={REDIRECT_URI}',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'http://api.odnoklassniki.ru/oauth/token.do',
    'authorization_header'         => FALSE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => 'SET STATUS',
    'method_url'                   => 'http://api.odnoklassniki.ru/fb.do?method={METHOD_NAME}&{METHOD_URI}&access_token={ACCESS_TOKEN}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'reddit'   => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    'dialog_url'                   => 'https://ssl.reddit.com/api/v1/authorize?client_id={CLIENT_ID}&duration=permanent&response_type=code&redirect_uri={REDIRECT_URI}&state={STATE}&scope={SCOPE}',
    'append_state_to_redirect_uri' => '',
    'access_token_url'             => 'https://ssl.reddit.com/api/v1/access_token',
    'authorization_header'         => 'Bearer',
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => 'identity,privatemessages',
    'method_url'                   => 'https://oauth.reddit.com{METHOD_NAME}?{METHOD_URI}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'tumblr'     => array(
    'oauth_version'                => '1.0a',
    'request_token_url'            => 'http://www.tumblr.com/oauth/request_token',
    'dialog_url'                   => 'http://www.tumblr.com/oauth/authorize',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'http://www.tumblr.com/oauth/access_token',
    'authorization_header'         => TRUE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => '',
    'method_url'                   => 'http://api.tumblr.com/v2/{METHOD_NAME}?{METHOD_URI}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'twitter'    => array(
    'oauth_version'                => '1.0a',
    'request_token_url'            => 'https://api.twitter.com/oauth/request_token',
    'dialog_url'                   => 'https://api.twitter.com/oauth/authenticate',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'https://api.twitter.com/oauth/access_token',
    'authorization_header'         => TRUE,
    'url_parameters'               => TRUE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => '',
    'method_url'                   => 'https://api.twitter.com/1.1/{METHOD_NAME}?{METHOD_URI}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'vkontakte'   => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    //'dialog_url'                   => 'https://oauth.vk.com/authorize?client_id={CLIENT_ID}&scope={SCOPE}&redirect_uri={REDIRECT_URI}&response_type=token&display=popup',
    'dialog_url'                   => 'https://oauth.vk.com/authorize?client_id={CLIENT_ID}&scope={SCOPE}&redirect_uri={REDIRECT_URI}&response_type=code&display=popup',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'https://oauth.vk.com/access_token',
    'authorization_header'         => FALSE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => 'photos,wall,offline,status',
    'method_url'                   => 'https://api.vk.com/method/{METHOD_NAME}?{METHOD_URI}&access_token={ACCESS_TOKEN}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'wordpress'      => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    'dialog_url'                   => 'https://public-api.wordpress.com/oauth2/authorize?client_id={CLIENT_ID}&state={STATE}&response_type=code&redirect_uri={REDIRECT_URI}',
    'append_state_to_redirect_uri' => '',
    'access_token_url'             => 'https://public-api.wordpress.com/oauth2/token',
    'authorization_header'         => 'Bearer',
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => '',
    'method_url'                   => 'https://public-api.wordpress.com/rest/v1/{METHOD_NAME}?{METHOD_URI}',
    'urlencode_redirect'           => FALSE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'yahoo'      => array(
    'oauth_version'                => '1.0a',
    'request_token_url'            => 'https://api.login.yahoo.com/oauth/v2/get_request_token',
    'dialog_url'                   => 'https://api.login.yahoo.com/oauth/v2/request_auth',
    'append_state_to_redirect_uri' => 'state',
    'access_token_url'             => 'https://api.login.yahoo.com/oauth/v2/get_token',
    'authorization_header'         => TRUE,
    'url_parameters'               => TRUE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => 'ysrw',
    'method_url'                   => 'http://social.yahooapis.com/v1/{METHOD_NAME}?{METHOD_URI}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'yaru'   => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    'dialog_url'                   => 'https://oauth.yandex.ru/authorize?client_id={CLIENT_ID}&response_type=code&display=popup&state={STATE}',
    'append_state_to_redirect_uri' => '',
    'access_token_url'             => 'https://oauth.yandex.ru/token',
    'authorization_header'         => FALSE,
    'url_parameters'               => FALSE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => '',
    'method_url'                   => 'https://api-yaru.yandex.ru/{METHOD_NAME}?{METHOD_URI}&oauth_token={ACCESS_TOKEN}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),
  'youtube'      => array(
    'oauth_version'                => '2.0',
    'request_token_url'            => '',
    'dialog_url'                   => 'https://accounts.google.com/o/oauth2/auth?client_id={CLIENT_ID}&response_type=code&access_type=offline&scope={SCOPE}&state={STATE}&redirect_uri={REDIRECT_URI}',
    'append_state_to_redirect_uri' => '',
    'access_token_url'             => 'https://accounts.google.com/o/oauth2/token',
    'authorization_header'         => TRUE,
    'url_parameters'               => TRUE,
    'client_id'                    => '',
    'client_secret'                => '',
    'redirect_uri'                 => '',
    'scope'                        => 'https://www.googleapis.com/auth/userinfo.profile',
    'method_url'                   => 'https://www.googleapis.com/youtube/v3/{METHOD_NAME}?{METHOD_URI}&access_token={ACCESS_TOKEN}',
    'urlencode_redirect'           => TRUE,
    'debug'                        => FALSE,
    'debug_http'                   => FALSE,
  ),

);
